### ISSUE TITLE
`vitro init` doesn't copy template

### ISSUE THREAD

**Issue by anteprimorac** [remorses/vitro#1]
Hi @remorses, first of all, thank you for this app.

I tried to use vitro by installing it globally, but `vitro init` doesn't copy the template folder because of this line:
https://github.com/remorses/vitro/blob/9217c8141154acf02a08c874260c8c34184c9d59/packages/cli/src/init.ts#L54
because when installed the template folder path looks like this `/usr/local/lib/node_modules/@vitro/cli/template`.

**Comment by remorses** [comment]
I changed that line, you can try now

It was working for me because i was using `yarn link`

**Comment by anteprimorac** [comment]
Excellent work it fixed the issue. Thank you.
